#!/bin/bash
# install:
# ctags htop autojump fzf neovim neovim-remote fish xbindkeys xclip wmctrl scrot ag gdb-dashboard rsync enca diffuse kdiff3 meld sdcv gpartedjgbпии 

declare -r FAV="/home/me/favconf"

ln -sf $FAV/lawk/lawk   /usr/local/bin/lawk       
ln -sf $FAV/gitcommit   /usr/local/bin/gitcommit  
ln -sf $FAV/p2left      /usr/local/bin/p2left     
ln -sf $FAV/p2right     /usr/local/bin/p2right    
ln -sf $FAV/sfvf/sf.lua /usr/local/bin/sf.lua    
ln -sf $FAV/sfvf/sf     /usr/local/bin/sf    
ln -sf $FAV/sfvf/vf     /usr/local/bin/vf    
ln -sf $FAV/tw/tw       /usr/local/bin/tw      
ln -sf $FAV/tw/twa      /usr/local/bin/twa     
ln -sf $FAV/vim/vims    /usr/local/bin/vims   
ln -sf $FAV/djvu/page.sh /usr/local/bin/page.sh   
ln -sf $FAV/djvu/allp.sh /usr/local/bin/allp.sh   
