#!/bin/bash
mkdir ~/.dwm
mkdir ~/.zshrc
mkdir ~/.xbindkeysrc
mkdir ~/.config/openbox
cp colormake/colormakerc   .colormakerc
cp dwm/config.h            ~/projects/dwm-6.0/
cp dwm/dwmstatus.c         ~/projects/dwmstatus/
cp dwm/autostart.sh        ~/.dwm/
cp git/.gitignore          ~/
cp vim/.vimrc              ~/
cp xbk/xbindkeysrc         ~/.xbindkeysrc 
cp zsh/.zshrc              ~/.zshrc
cp openbox/work.xml        ~/.config/openbox/
cp openbox/lubuntu-rc.xml  ~/.config/openbox/
