#!/bin/bash
declare -r FAV=~/favconf

function check_create() {
    if [ ! -d "$1" ]; then
        mkdir "$1"
    fi
}

ln -sf $FAV/git/.gitignore          ~/
ln -sf $FAV/git/gitconfig          ~/.gitconfig
ln -sf $FAV/vim/.vimrc              ~/

ln -sf $FAV/xbk/xbindkeysrc         ~/.xbindkeysrc
#ln -sf $FAV/zsh/.zshrc.local        ~/.zshrc.local
ln -sf $FAV/config.fish             ~/config.fish
ln -sf $FAV/config.fish             ~/.config/fish/config.fish

check_create ~/.config/nvim
check_create ~/.vim/bundle
ln -sf $FAV/nvim/init.vim           ~/.config/nvim/init.vim

cp $FAV/vim/plug.vim                ~/.vim/autoload/

check_create ~/.mc
ln -sf $FAV/mc/ini                  ~/.mc/ini

