#!/bin/bash
wmctrl -r :ACTIVE: -b remove,maximized_vert,maximized_horz
wmctrl -r :ACTIVE: -b remove,fullscreen
X=$(xrandr | grep '*' | awk '{ print $1 }' | sed 's/x.\+//g')
Y=$(xrandr | grep '*' | awk '{ print $1 }' | sed 's/.\+x//g')
X2=$((X/2))
wmctrl -r :ACTIVE: -e "0,$X2,0,$X2,$Y"
