#!/bin/bash 

declare PATT="$1"
declare FINDARG="$2"

# without arg show last log
if [ "$PATT" = "" ]; then 
    if test -e ".sfvf"; then cat ".sfvf"; fi
    exit 0
fi

if [ "$FINDARG" != "" ]; then 
    FINDARG="-and $FINDARG"
fi

# remove last log
if test -e ".sfvf"; then rm ".sfvf"; fi

##find -L . -not -regex './\.g.+' $FINDARG 
# search
for line in $(find -L . -not -regex './\.g.+' $FINDARG); do  
    lawk "/usr/local/bin/sf.lua" "$line" "$PATT"
done
