#!/bin/bash

# without arg show last log
if [ "$1" = "" ]; then 
    if test -e ".sfvf"; then cat ".sfvf"; fi
    exit 0
fi


if [ "$2" = "" ]; then 
	declare FILES='-name "*.c" -o -name "*.h" -o -name "*.cpp"'
else
	declare FILES='$2'
fi

# remove last log
if test -e ".sfvf"; then rm ".sfvf"; fi

# serch
for line in $(find -L . $FILES); do  
    lawk "/usr/local/bin/sf.lua" "$line" "$1"
done
